# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Entercorrectdata' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'entercorrectdata' do
    @driver.get('http://localhost:10009/')
    @driver.manage.resize_to(1440, 797)
    @driver.find_element(:id, 'n').click
    @driver.find_element(:id, 'a').click
    @driver.find_element(:id, 'a').send_keys('1 5 5 25 125 10 10')
    @driver.find_element(:id, 'n').click
    @driver.find_element(:id, 'n').click
    element = @driver.find_element(:id, 'n')
    @driver.action.double_click(element).perform
    @driver.find_element(:id, 'n').send_keys('7')
    @driver.find_element(:name, 'commit').click
    element = @driver.find_element(:name, 'commit')
    @driver.action.move_to_element(element).perform
  end
end
